module.exports = {
  "font-size": {
    "overline": { "value": "{font.size.5xs.value}" },
    "caption": { "value": "{font.size.4xs.value}" },
    "body-sm": { "value": "{font.size.3xs.value}" },
    "body-md": { "value": "{font.size.2xs.value}" },
    "body-lg": { "value": "{font.size.xs.value}" },
    "subtitle-md": { "value": "{font.size.base.value}" },
    "subtitle-lg": { "value": "{font.size.lg.value}" },
    "h6": { "value": "{font.size.xl.value}" },
    "h5": { "value": "{font.size.2xl.value}" },
    "h4": { "value": "{font.size.3xl.value}" },
    "h3": { "value": "{font.size.4xl.value}" },
    "h2": { "value": "{font.size.5xl.value}" },
    "h1": { "value": "{font.size.6xl.value}" },
  },
  "line-height": {
    "overline": { "value": "{line-height.9xl.value}" },
    "caption": { "value": "{line-height.6xl.value}" },
    "body-sm": { "value": "{line-height.7xl.value}" },
    "body-md": { "value": "{line-height.8xl.value}" },
    "body-lg": { "value": "{line-height.7xl.value}" },
    "subtitle-md": { "value": "{line-height.5xl.value}" },
    "subtitle-lg": { "value": "{line-height.4xl.value}" },
    "h6": { "value": "{line-height.3xl.value}" },
    "h5": { "value": "{line-height.2xl.value}" },
    "h4": { "value": "{line-height.xl.value}" },
    "h3": { "value": "{line-height.base.value}" },
    "h2": { "value": "{line-height.lg.value}" },
    "h1": { "value": "{line-height.base.value}" },
  },
  "letter-spacing": {
    "h6": { "value": "{letter-spacing.base.value}" },
    "h5": { "value": "{letter-spacing.sm.value}" },
    "h4": { "value": "{letter-spacing.xs.value}" },
    "h3": { "value": "{letter-spacing.base.value}" },
    "h2": { "value": "{letter-spacing.base.value}" },
    "h1": { "value": "{letter-spacing.2xs.value}" },
  },
};
